@main struct CarbonObservationTests {
    static func main() {
        precondition(ProbeChord(rawValue: "ctrl-option-f11") == .f11)
        precondition(ProbeChord(rawValue: "ctrl-option-k") == .letterK)
        precondition(ProbeChord(rawValue: "arbitrary-key") == nil)
        precondition(ProbeChord.f11.keyCode == 103 && ProbeChord.letterK.keyCode == 40)
        var letter = CarbonObservations()
        letter.recordLocal(down: true, f11Character: false, function: false,
                           numericPad: false, kCharacter: true)
        precondition(letter.localKCharacter && !letter.localF11Character)
        var observation = CarbonObservations()
        precondition(observation.handlerEntered == 0 && observation.carbonPressed == 0)
        observation.enterCarbon()
        precondition(observation.handlerEntered == 1 && observation.parameterFailed == 0)
        precondition(!observation.decodeCarbon(succeeded: false, signature: 0x50724F62, id: 1))
        precondition(observation.parameterFailed == 1 && observation.idMismatch == 0)
        observation.enterCarbon()
        precondition(!observation.decodeCarbon(succeeded: true, signature: 0, id: 1))
        observation.enterCarbon()
        precondition(!observation.decodeCarbon(succeeded: true, signature: 0x50724F62, id: 2))
        precondition(observation.handlerEntered == 3 && observation.idMismatch == 2)
        precondition(observation.carbonPressed == 0 && observation.parameterFailed == 1)
        observation.enterCarbon()
        precondition(observation.decodeCarbon(succeeded: true, signature: 0x50724F62, id: 1))
        observation.recordLocal(down: true, f11Character: true, function: false, numericPad: false)
        observation.recordLocal(down: false, f11Character: false, function: true, numericPad: true)
        precondition(observation.localDown == 1 && observation.localUp == 1)
        precondition(observation.localF11Character && observation.localFunction && observation.localNumericPad)
        precondition(!observation.localKCharacter)
        for _ in 0..<2000 {
            observation.enterCarbon()
            _ = observation.decodeCarbon(succeeded: true, signature: 0x50724F62, id: 1)
            _ = observation.decodeCarbon(succeeded: false, signature: 0, id: 0)
            _ = observation.decodeCarbon(succeeded: true, signature: 0, id: 0)
            observation.recordLocal(down: true, f11Character: false, function: false, numericPad: false)
            observation.recordLocal(down: false, f11Character: false, function: false, numericPad: false)
        }
        precondition(observation.handlerEntered == 1024 && observation.carbonPressed == 1024)
        precondition(observation.parameterFailed == 1024 && observation.idMismatch == 1024)
        precondition(observation.localDown == 1024 && observation.localUp == 1024)
        precondition(observation.localF11Character && observation.localFunction && observation.localNumericPad)
        print("Owned Carbon observation transitions passed")
    }
}
